trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  Codeql.Enabled: true

schedules: 
- cron: "0 0 * * WEDNESDAY"
  displayName: CodeQL weekly scan 
  branches:
    include: 
    - main

steps:
- script: echo placeholder
  displayName: 'placeholder'
